server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhos:3306/seckill?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: admin

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html