server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

mybatis:
  config-location: classpath:mapper/*Mapper.xml

com:
  seckill:
    fixed-salt: dsfh342dfas

    cookie:
      max-age: 86400
      prefix: SECKILL_
      key-name: SECKILL_TOKEN

    redis-lock:
      key-prefix: redis_lock_
      expire: 3600

    performance:
      cookie-output-path: performance_test/cookies.csv